# Generated by Django 4.1.2 on 2022-10-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_year', models.CharField(max_length=300)),
                ('make', models.CharField(max_length=300)),
                ('model', models.CharField(max_length=300)),
                ('rejection_percentage', models.CharField(max_length=300)),
                ('reason_1', models.CharField(max_length=300)),
                ('reason_2', models.CharField(max_length=300)),
                ('reason_3', models.CharField(max_length=300)),
            ],
        ),
    ]
